# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.8.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QDial, QFrame, QGridLayout,
    QLCDNumber, QLabel, QMainWindow, QProgressBar,
    QSizePolicy, QSlider, QVBoxLayout, QWidget)
import rc_resources

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setWindowModality(Qt.WindowModal)
        MainWindow.resize(440, 380)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(440, 380))
        MainWindow.setMaximumSize(QSize(440, 380))
        MainWindow.setContextMenuPolicy(Qt.NoContextMenu)
        MainWindow.setWindowTitle(u"LMDE-COMP")
#if QT_CONFIG(whatsthis)
        MainWindow.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        MainWindow.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)
        MainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setEnabled(True)
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(220, 200, 201, 20))
        font = QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_5.setFont(font)
#if QT_CONFIG(accessibility)
        self.label_5.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.label_5.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)
        self.label_5.setScaledContents(False)
        self.label_5.setAlignment(Qt.AlignCenter)
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 200, 201, 20))
        self.label_6.setFont(font)
        self.label_6.setAlignment(Qt.AlignCenter)
        self.dial_fan = QDial(self.centralwidget)
        self.dial_fan.setObjectName(u"dial_fan")
        self.dial_fan.setGeometry(QRect(220, 230, 201, 101))
        self.dial_fan.setMouseTracking(False)
#if QT_CONFIG(accessibility)
        self.dial_fan.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.dial_fan.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)
        self.dial_fan.setMaximum(100)
        self.dial_fan.setOrientation(Qt.Horizontal)
        self.dial_fan.setInvertedAppearance(False)
        self.dial_fan.setInvertedControls(False)
        self.dial_fan.setWrapping(False)
        self.dial_fan.setNotchTarget(5.000000000000000)
        self.dial_fan.setNotchesVisible(True)
        self.progressBar_fan = QProgressBar(self.centralwidget)
        self.progressBar_fan.setObjectName(u"progressBar_fan")
        self.progressBar_fan.setGeometry(QRect(220, 340, 201, 23))
#if QT_CONFIG(accessibility)
        self.progressBar_fan.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.progressBar_fan.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)
        self.progressBar_fan.setValue(0)
        self.label_13 = QLabel(self.centralwidget)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(220, 10, 201, 20))
        self.label_13.setFont(font)
#if QT_CONFIG(accessibility)
        self.label_13.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.label_13.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)
        self.label_13.setAlignment(Qt.AlignCenter)
        self.label_14 = QLabel(self.centralwidget)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(20, 10, 171, 181))
#if QT_CONFIG(accessibility)
        self.label_14.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.label_14.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)
        self.label_14.setPixmap(QPixmap(u":/ui/lampara.png"))
        self.label_14.setScaledContents(True)
        self.label_14.setAlignment(Qt.AlignCenter)
        self.verticalLayoutWidget = QWidget(self.centralwidget)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(10, 230, 201, 131))
        self.verticalLayout_3 = QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout = QGridLayout()
        self.gridLayout.setObjectName(u"gridLayout")
        self.horizontalSlider_i = QSlider(self.verticalLayoutWidget)
        self.horizontalSlider_i.setObjectName(u"horizontalSlider_i")
        self.horizontalSlider_i.setMaximum(31)
        self.horizontalSlider_i.setValue(31)
        self.horizontalSlider_i.setOrientation(Qt.Horizontal)

        self.gridLayout.addWidget(self.horizontalSlider_i, 3, 1, 1, 1)

        self.label_20 = QLabel(self.verticalLayoutWidget)
        self.label_20.setObjectName(u"label_20")
#if QT_CONFIG(accessibility)
        self.label_20.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.label_20.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)

        self.gridLayout.addWidget(self.label_20, 2, 0, 1, 1)

        self.horizontalSlider_g = QSlider(self.verticalLayoutWidget)
        self.horizontalSlider_g.setObjectName(u"horizontalSlider_g")
        self.horizontalSlider_g.setMaximum(255)
        self.horizontalSlider_g.setOrientation(Qt.Horizontal)

        self.gridLayout.addWidget(self.horizontalSlider_g, 1, 1, 1, 1)

        self.label_22 = QLabel(self.verticalLayoutWidget)
        self.label_22.setObjectName(u"label_22")
#if QT_CONFIG(accessibility)
        self.label_22.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.label_22.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)

        self.gridLayout.addWidget(self.label_22, 0, 0, 1, 1)

        self.horizontalSlider_r = QSlider(self.verticalLayoutWidget)
        self.horizontalSlider_r.setObjectName(u"horizontalSlider_r")
        self.horizontalSlider_r.setMaximum(255)
        self.horizontalSlider_r.setOrientation(Qt.Horizontal)

        self.gridLayout.addWidget(self.horizontalSlider_r, 0, 1, 1, 1)

        self.label_19 = QLabel(self.verticalLayoutWidget)
        self.label_19.setObjectName(u"label_19")
#if QT_CONFIG(accessibility)
        self.label_19.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.label_19.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)

        self.gridLayout.addWidget(self.label_19, 1, 0, 1, 1)

        self.label_21 = QLabel(self.verticalLayoutWidget)
        self.label_21.setObjectName(u"label_21")
#if QT_CONFIG(accessibility)
        self.label_21.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.label_21.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)

        self.gridLayout.addWidget(self.label_21, 3, 0, 1, 1)

        self.horizontalSlider_b = QSlider(self.verticalLayoutWidget)
        self.horizontalSlider_b.setObjectName(u"horizontalSlider_b")
        self.horizontalSlider_b.setMaximum(255)
        self.horizontalSlider_b.setOrientation(Qt.Horizontal)

        self.gridLayout.addWidget(self.horizontalSlider_b, 2, 1, 1, 1)

        self.label_r = QLabel(self.verticalLayoutWidget)
        self.label_r.setObjectName(u"label_r")
#if QT_CONFIG(accessibility)
        self.label_r.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.label_r.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)
        self.label_r.setText(u"0")
        self.label_r.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.gridLayout.addWidget(self.label_r, 0, 2, 1, 1)

        self.label_g = QLabel(self.verticalLayoutWidget)
        self.label_g.setObjectName(u"label_g")
#if QT_CONFIG(accessibility)
        self.label_g.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.label_g.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)
        self.label_g.setText(u"0")
        self.label_g.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.gridLayout.addWidget(self.label_g, 1, 2, 1, 1)

        self.label_b = QLabel(self.verticalLayoutWidget)
        self.label_b.setObjectName(u"label_b")
#if QT_CONFIG(accessibility)
        self.label_b.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.label_b.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)
        self.label_b.setText(u"0")
        self.label_b.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.gridLayout.addWidget(self.label_b, 2, 2, 1, 1)

        self.label_i = QLabel(self.verticalLayoutWidget)
        self.label_i.setObjectName(u"label_i")
#if QT_CONFIG(accessibility)
        self.label_i.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.label_i.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)
        self.label_i.setText(u"31")
        self.label_i.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.gridLayout.addWidget(self.label_i, 3, 2, 1, 1)

        self.gridLayout.setColumnMinimumWidth(2, 26)

        self.verticalLayout_3.addLayout(self.gridLayout)

        self.color = QLabel(self.verticalLayoutWidget)
        self.color.setObjectName(u"color")
#if QT_CONFIG(whatsthis)
        self.color.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.color.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)
        self.color.setStyleSheet(u"background-color: rgb(0, 0, 0);")
        self.color.setAlignment(Qt.AlignCenter)

        self.verticalLayout_3.addWidget(self.color)

        self.gridLayoutWidget = QWidget(self.centralwidget)
        self.gridLayoutWidget.setObjectName(u"gridLayoutWidget")
        self.gridLayoutWidget.setGeometry(QRect(210, 40, 220, 151))
        self.gridLayout_2 = QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.lcd_luminosity = QLCDNumber(self.gridLayoutWidget)
        self.lcd_luminosity.setObjectName(u"lcd_luminosity")
        self.lcd_luminosity.setEnabled(False)
        self.lcd_luminosity.setMaximumSize(QSize(50, 16777215))
#if QT_CONFIG(accessibility)
        self.lcd_luminosity.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.lcd_luminosity.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)
        self.lcd_luminosity.setInputMethodHints(Qt.ImhNone)
        self.lcd_luminosity.setDigitCount(5)
        self.lcd_luminosity.setSegmentStyle(QLCDNumber.Flat)
        self.lcd_luminosity.setProperty(u"value", 0.000000000000000)

        self.gridLayout_2.addWidget(self.lcd_luminosity, 2, 1, 1, 1)

        self.lcd_co2 = QLCDNumber(self.gridLayoutWidget)
        self.lcd_co2.setObjectName(u"lcd_co2")
        self.lcd_co2.setEnabled(False)
        self.lcd_co2.setMaximumSize(QSize(50, 16777215))
#if QT_CONFIG(accessibility)
        self.lcd_co2.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.lcd_co2.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)
        self.lcd_co2.setInputMethodHints(Qt.ImhNone)
        self.lcd_co2.setDigitCount(5)
        self.lcd_co2.setSegmentStyle(QLCDNumber.Flat)
        self.lcd_co2.setProperty(u"value", 0.000000000000000)

        self.gridLayout_2.addWidget(self.lcd_co2, 3, 1, 1, 1)

        self.label = QLabel(self.gridLayoutWidget)
        self.label.setObjectName(u"label")
        self.label.setMaximumSize(QSize(300, 16777215))
#if QT_CONFIG(accessibility)
        self.label.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.label.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)

        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)

        self.lcd_temp = QLCDNumber(self.gridLayoutWidget)
        self.lcd_temp.setObjectName(u"lcd_temp")
        self.lcd_temp.setEnabled(False)
        self.lcd_temp.setMaximumSize(QSize(50, 16777215))
        font1 = QFont()
        font1.setBold(False)
        self.lcd_temp.setFont(font1)
#if QT_CONFIG(accessibility)
        self.lcd_temp.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.lcd_temp.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)
        self.lcd_temp.setAutoFillBackground(False)
        self.lcd_temp.setFrameShape(QFrame.Box)
        self.lcd_temp.setFrameShadow(QFrame.Raised)
        self.lcd_temp.setSmallDecimalPoint(False)
        self.lcd_temp.setDigitCount(5)
        self.lcd_temp.setMode(QLCDNumber.Dec)
        self.lcd_temp.setSegmentStyle(QLCDNumber.Flat)
        self.lcd_temp.setProperty(u"value", 0.000000000000000)
        self.lcd_temp.setProperty(u"intValue", 0)

        self.gridLayout_2.addWidget(self.lcd_temp, 0, 1, 1, 1)

        self.progressBar_noise = QProgressBar(self.gridLayoutWidget)
        self.progressBar_noise.setObjectName(u"progressBar_noise")
        self.progressBar_noise.setMaximumSize(QSize(50, 16777215))
        self.progressBar_noise.setStyleSheet(u"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(51, 209, 122, 255), stop:0.333 rgba(51, 209, 122, 255), stop:0.334 rgba(255, 120, 0, 255), stop:0.666 rgba(255, 120, 0, 255), stop:0.667 rgba(224, 27, 36, 255), stop:1 rgba(224, 27, 36, 255));\n"
"\n"
"selection-background-color: rgb(42, 42, 42);")
        self.progressBar_noise.setValue(100)
        self.progressBar_noise.setTextVisible(False)
        self.progressBar_noise.setInvertedAppearance(True)

        self.gridLayout_2.addWidget(self.progressBar_noise, 4, 1, 1, 1)

        self.label_4 = QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setMaximumSize(QSize(300, 16777215))
#if QT_CONFIG(accessibility)
        self.label_4.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.label_4.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)

        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 1)

        self.label_2 = QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setMaximumSize(QSize(300, 16777215))
#if QT_CONFIG(accessibility)
        self.label_2.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.label_2.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)

        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)

        self.label_7 = QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setMaximumSize(QSize(300, 16777215))
#if QT_CONFIG(accessibility)
        self.label_7.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.label_7.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)

        self.gridLayout_2.addWidget(self.label_7, 4, 0, 1, 1)

        self.lcd_humidity = QLCDNumber(self.gridLayoutWidget)
        self.lcd_humidity.setObjectName(u"lcd_humidity")
        self.lcd_humidity.setEnabled(False)
        self.lcd_humidity.setMaximumSize(QSize(50, 16777215))
#if QT_CONFIG(accessibility)
        self.lcd_humidity.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.lcd_humidity.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)
        self.lcd_humidity.setInputMethodHints(Qt.ImhNone)
        self.lcd_humidity.setDigitCount(5)
        self.lcd_humidity.setSegmentStyle(QLCDNumber.Flat)
        self.lcd_humidity.setProperty(u"value", 0.000000000000000)
        self.lcd_humidity.setProperty(u"intValue", 0)

        self.gridLayout_2.addWidget(self.lcd_humidity, 1, 1, 1, 1)

        self.label_3 = QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setMaximumSize(QSize(300, 16777215))
#if QT_CONFIG(accessibility)
        self.label_3.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        self.label_3.setAccessibleDescription(u"")
#endif // QT_CONFIG(accessibility)

        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)

        self.label_8 = QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName(u"label_8")

        self.gridLayout_2.addWidget(self.label_8, 0, 2, 1, 1)

        self.label_9 = QLabel(self.gridLayoutWidget)
        self.label_9.setObjectName(u"label_9")

        self.gridLayout_2.addWidget(self.label_9, 1, 2, 1, 1)

        self.label_10 = QLabel(self.gridLayoutWidget)
        self.label_10.setObjectName(u"label_10")

        self.gridLayout_2.addWidget(self.label_10, 2, 2, 1, 1)

        self.label_11 = QLabel(self.gridLayoutWidget)
        self.label_11.setObjectName(u"label_11")

        self.gridLayout_2.addWidget(self.label_11, 3, 2, 1, 1)

        self.label_12 = QLabel(self.gridLayoutWidget)
        self.label_12.setObjectName(u"label_12")

        self.gridLayout_2.addWidget(self.label_12, 4, 2, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.dial_fan.valueChanged.connect(self.progressBar_fan.setValue)
        self.horizontalSlider_r.valueChanged.connect(self.label_r.setNum)
        self.horizontalSlider_g.valueChanged.connect(self.label_g.setNum)
        self.horizontalSlider_b.valueChanged.connect(self.label_b.setNum)
        self.horizontalSlider_i.valueChanged.connect(self.label_i.setNum)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Ventilador", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Leds", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Sensores", None))
        self.label_14.setText("")
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"B", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"R", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"G", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"I", None))
        self.color.setText("")
        self.label.setText(QCoreApplication.translate("MainWindow", u"Temperatura", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"CO2", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Humedad Relativa", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Ruido", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Luminosidad", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"\u00baC", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"%", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"lx", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"ppm", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"lvl", None))
        pass
    # retranslateUi

